version: "3.9"

services:
  backend:
    build: ./backend
    container_name: dataforge_backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: dataforge_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: dataforge_redis
    ports:
      - "6360:6379"

  worker:
    build: ./backend
    command: sh -c "python manage.py migrate && celery -A core worker --loglevel=info"
    depends_on:
      - backend
      - redis
    env_file:
      - ./backend/.env
